# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-03-08 15:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userAccount', models.CharField(max_length=11)),
                ('goodsId', models.CharField(max_length=11)),
                ('goodsName', models.CharField(max_length=50)),
                ('goodsImg', models.CharField(max_length=50)),
                ('goodsPrice', models.CharField(max_length=50)),
                ('goodsNum', models.IntegerField()),
            ],
            options={
                'db_table': 'axf_cart',
            },
        ),
        migrations.CreateModel(
            name='FoodTypes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('typeid', models.CharField(max_length=50)),
                ('typename', models.CharField(max_length=50)),
                ('childtypenames', models.CharField(max_length=150)),
                ('typesort', models.IntegerField()),
            ],
            options={
                'db_table': 'axf_foodtypes',
            },
        ),
        migrations.CreateModel(
            name='Goods',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productid', models.CharField(max_length=50)),
                ('productimg', models.CharField(max_length=100)),
                ('productname', models.CharField(max_length=50)),
                ('productlongname', models.CharField(max_length=50)),
                ('isxf', models.BooleanField(default=False)),
                ('pmdesc', models.BooleanField(default=False)),
                ('specifics', models.CharField(max_length=20)),
                ('price', models.CharField(max_length=20)),
                ('marketprice', models.CharField(max_length=20)),
                ('categoryid', models.CharField(max_length=50)),
                ('childcid', models.CharField(max_length=50)),
                ('childcidname', models.CharField(max_length=50)),
                ('dealerid', models.CharField(max_length=50)),
                ('storenums', models.CharField(max_length=50)),
                ('productnum', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'axf_goods',
            },
        ),
        migrations.CreateModel(
            name='MainShow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trackid', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=50)),
                ('img', models.CharField(max_length=100)),
                ('categoryid', models.CharField(max_length=50)),
                ('brandname', models.CharField(max_length=50)),
                ('img1', models.CharField(max_length=100)),
                ('childcid1', models.CharField(max_length=50)),
                ('productid1', models.CharField(max_length=50)),
                ('longname1', models.CharField(max_length=70)),
                ('price1', models.CharField(max_length=50)),
                ('marketprice1', models.CharField(max_length=50)),
                ('img2', models.CharField(max_length=50)),
                ('childcid2', models.CharField(max_length=50)),
                ('productid2', models.CharField(max_length=50)),
                ('longname2', models.CharField(max_length=50)),
                ('price2', models.CharField(max_length=50)),
                ('marketprice2', models.CharField(max_length=50)),
                ('img3', models.CharField(max_length=50)),
                ('childcid3', models.CharField(max_length=50)),
                ('productid3', models.CharField(max_length=50)),
                ('longname3', models.CharField(max_length=50)),
                ('price3', models.CharField(max_length=50)),
                ('marketprice3', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'axf_mainshow',
            },
        ),
        migrations.CreateModel(
            name='MustBuy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=50)),
                ('trackid', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'axf_mustbuy',
            },
        ),
        migrations.CreateModel(
            name='Nav',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=50)),
                ('trackid', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'axf_nav',
            },
        ),
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=50)),
                ('trackid', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'axf_shop',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userAccount', models.CharField(max_length=11)),
                ('userPass', models.CharField(max_length=32)),
                ('userName', models.CharField(max_length=20)),
                ('userPhone', models.CharField(max_length=11)),
                ('userAdderss', models.CharField(max_length=200)),
                ('userImg', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'axf_user',
            },
        ),
        migrations.CreateModel(
            name='Wheel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=50)),
                ('trackid', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'axf_wheel',
            },
        ),
    ]
